"""0003_invitations_support_tickets

Revision ID: b49ef0fcc0b4
Revises: c85279be5773
Create Date: 2026-05-26 13:03:24.832399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b49ef0fcc0b4'
down_revision: Union[str, None] = 'c85279be5773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Existing type (created in baseline) — referenced, never re-created/dropped here.
user_role_t = postgresql.ENUM(
    'owner', 'agent', 'viewer', name='user_role', create_type=False,
)
# New types — created at top of upgrade, dropped at end of downgrade (repeatable).
invitation_status_t = postgresql.ENUM(
    'pending', 'accepted', 'revoked', 'expired', name='invitation_status', create_type=False,
)
support_ticket_status_t = postgresql.ENUM(
    'open', 'pending', 'resolved', 'closed', name='support_ticket_status', create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    invitation_status_t.create(bind, checkfirst=True)
    support_ticket_status_t.create(bind, checkfirst=True)
    op.create_table('invitations',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', user_role_t, nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('status', invitation_status_t, server_default='pending', nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('accepted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], name=op.f('fk_invitations_accepted_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_invitations_invited_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_invitations_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations')),
    sa.UniqueConstraint('token', name='uq_invitations_token')
    )
    op.create_index('ix_invitations_email_status', 'invitations', ['email', 'status'], unique=False)
    op.create_index(op.f('ix_invitations_status'), 'invitations', ['status'], unique=False)
    op.create_index('ix_invitations_vendor_email', 'invitations', ['vendor_id', 'email'], unique=False)
    op.create_index(op.f('ix_invitations_vendor_id'), 'invitations', ['vendor_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('opened_by_user_id', sa.UUID(), nullable=True),
    sa.Column('assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', support_ticket_status_t, server_default='open', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], name=op.f('fk_support_tickets_assignee_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], name=op.f('fk_support_tickets_opened_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_support_tickets_vendor_id_vendors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_tickets'))
    )
    op.create_index(op.f('ix_support_tickets_assignee_user_id'), 'support_tickets', ['assignee_user_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index('ix_support_tickets_status_created', 'support_tickets', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_support_tickets_vendor_id'), 'support_tickets', ['vendor_id'], unique=False)
    op.create_table('support_ticket_messages',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_support_ticket_messages_author_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], name=op.f('fk_support_ticket_messages_ticket_id_support_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_ticket_messages'))
    )
    op.create_index(op.f('ix_support_ticket_messages_ticket_id'), 'support_ticket_messages', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_ticket_messages_ticket_id'), table_name='support_ticket_messages')
    op.drop_table('support_ticket_messages')
    op.drop_index(op.f('ix_support_tickets_vendor_id'), table_name='support_tickets')
    op.drop_index('ix_support_tickets_status_created', table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_assignee_user_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_invitations_vendor_id'), table_name='invitations')
    op.drop_index('ix_invitations_vendor_email', table_name='invitations')
    op.drop_index(op.f('ix_invitations_status'), table_name='invitations')
    op.drop_index('ix_invitations_email_status', table_name='invitations')
    op.drop_table('invitations')
    # Drop only the types introduced here (user_role stays — still used elsewhere).
    bind = op.get_bind()
    support_ticket_status_t.drop(bind, checkfirst=True)
    invitation_status_t.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
