"""0002_platform_admin_workspace_requests

Revision ID: c85279be5773
Revises: e76c54a0aa89
Create Date: 2026-05-26 12:49:02.011147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c85279be5773'
down_revision: Union[str, None] = 'e76c54a0aa89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Enum type handles (create_type=False — created/dropped explicitly below so the
# migration is cleanly repeatable; otherwise downgrade leaves orphan types).
workspace_request_status_t = postgresql.ENUM(
    'pending', 'approved', 'rejected', 'cancelled',
    name='workspace_request_status', create_type=False,
)
platform_role_t = postgresql.ENUM(
    'none', 'support', 'admin', 'superadmin', name='platform_role', create_type=False,
)
vendor_status_t = postgresql.ENUM(
    'active', 'suspended', 'deleted', name='vendor_status', create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    workspace_request_status_t.create(bind, checkfirst=True)
    platform_role_t.create(bind, checkfirst=True)
    vendor_status_t.create(bind, checkfirst=True)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_audit_logs_vendor_id_vendors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_actor_created', 'audit_logs', ['actor_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_target', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_audit_logs_vendor_created', 'audit_logs', ['vendor_id', 'created_at'], unique=False)
    op.create_table('workspace_requests',
    sa.Column('requested_by_user_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('desired_slug', sa.String(length=100), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('status', workspace_request_status_t, server_default='pending', nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_vendor_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_vendor_id'], ['vendors.id'], name=op.f('fk_workspace_requests_created_vendor_id_vendors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_workspace_requests_requested_by_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_workspace_requests_reviewed_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_requests'))
    )
    op.create_index(op.f('ix_workspace_requests_requested_by_user_id'), 'workspace_requests', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_workspace_requests_status'), 'workspace_requests', ['status'], unique=False)
    op.create_index('ix_workspace_requests_status_created', 'workspace_requests', ['status', 'created_at'], unique=False)
    op.add_column('users', sa.Column('platform_role', platform_role_t, server_default='none', nullable=False))
    op.create_index(op.f('ix_users_platform_role'), 'users', ['platform_role'], unique=False)
    op.add_column('vendors', sa.Column('status', vendor_status_t, server_default='active', nullable=False))
    op.create_index(op.f('ix_vendors_status'), 'vendors', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_status'), table_name='vendors')
    op.drop_column('vendors', 'status')
    op.drop_index(op.f('ix_users_platform_role'), table_name='users')
    op.drop_column('users', 'platform_role')
    op.drop_index('ix_workspace_requests_status_created', table_name='workspace_requests')
    op.drop_index(op.f('ix_workspace_requests_status'), table_name='workspace_requests')
    op.drop_index(op.f('ix_workspace_requests_requested_by_user_id'), table_name='workspace_requests')
    op.drop_table('workspace_requests')
    op.drop_index('ix_audit_logs_vendor_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_target', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    # Drop enum types last, after all dependent columns are gone.
    bind = op.get_bind()
    vendor_status_t.drop(bind, checkfirst=True)
    platform_role_t.drop(bind, checkfirst=True)
    workspace_request_status_t.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
