"""0001_initial_base

Revision ID: e76c54a0aa89
Revises: 
Create Date: 2026-05-25 22:43:54.550601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e76c54a0aa89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Reusable enum type handles. create_type=False keeps create_table() from
# emitting CREATE TYPE; we create/drop them explicitly in upgrade/downgrade.
outbox_status = postgresql.ENUM(
    'pending', 'processing', 'sent', 'failed', name='outbox_status', create_type=False
)
user_role = postgresql.ENUM(
    'owner', 'agent', 'viewer', name='user_role', create_type=False
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types once, up front. The columns below reference them with
    # create_type=False so table creation does not re-emit CREATE TYPE, and the
    # downgrade drops them explicitly — making the baseline cleanly repeatable.
    bind = op.get_bind()
    outbox_status.create(bind, checkfirst=True)
    user_role.create(bind, checkfirst=True)
    op.create_table('processed_events',
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('dedup_hash', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processed_events')),
    sa.UniqueConstraint('source', 'external_id', name='uq_processed_events_source')
    )
    op.create_index(op.f('ix_processed_events_dedup_hash'), 'processed_events', ['dedup_hash'], unique=False)
    op.create_table('users',
    sa.Column('clerk_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vendors',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors'))
    )
    op.create_index(op.f('ix_vendors_slug'), 'vendors', ['slug'], unique=True)
    op.create_table('applications',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('education', sa.String(length=255), nullable=True),
    sa.Column('course', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('intake', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_applications_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_index(op.f('ix_applications_vendor_id'), 'applications', ['vendor_id'], unique=False)
    op.create_table('callbacks',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('preferred_time', sa.String(length=120), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_callbacks_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_callbacks'))
    )
    op.create_index(op.f('ix_callbacks_vendor_id'), 'callbacks', ['vendor_id'], unique=False)
    op.create_table('cost_estimates',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('study_level', sa.String(length=60), nullable=True),
    sa.Column('course', sa.String(length=255), nullable=True),
    sa.Column('intake', sa.String(length=120), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('est_tuition', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('est_stay', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('est_food', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('est_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_cost_estimates_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_estimates'))
    )
    op.create_index(op.f('ix_cost_estimates_vendor_id'), 'cost_estimates', ['vendor_id'], unique=False)
    op.create_table('inquiries',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_inquiries_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inquiries'))
    )
    op.create_index(op.f('ix_inquiries_vendor_id'), 'inquiries', ['vendor_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=True),
    sa.Column('aggregate_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', outbox_status, nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_outbox_events_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events')),
    sa.UniqueConstraint('dedup_key', name='uq_outbox_events_dedup_key')
    )
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_index('ix_outbox_events_status_available', 'outbox_events', ['status', 'available_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_vendor_id'), 'outbox_events', ['vendor_id'], unique=False)
    op.create_table('qr_logs',
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_qr_logs_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qr_logs'))
    )
    op.create_index(op.f('ix_qr_logs_vendor_id'), 'qr_logs', ['vendor_id'], unique=False)
    op.create_table('vendor_cost_settings',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('study_level', sa.String(length=60), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('tuition_per_year', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rent_per_month', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('food_per_month', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_cost_settings_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_cost_settings')),
    sa.UniqueConstraint('vendor_id', 'country', 'study_level', name='uq_vendor_cost_country_level')
    )
    op.create_index(op.f('ix_vendor_cost_settings_vendor_id'), 'vendor_cost_settings', ['vendor_id'], unique=False)
    op.create_table('vendor_memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('role', user_role, nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vendor_memberships_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_memberships_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_memberships')),
    sa.UniqueConstraint('user_id', 'vendor_id', name='uq_vendor_memberships_user_id')
    )
    op.create_index(op.f('ix_vendor_memberships_user_id'), 'vendor_memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_vendor_memberships_vendor_id'), 'vendor_memberships', ['vendor_id'], unique=False)
    op.create_index('ix_vendor_memberships_vendor_user', 'vendor_memberships', ['vendor_id', 'user_id'], unique=False)
    op.create_table('vendor_site_configs',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('draft_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_vendor_site_configs_updated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_site_configs_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vendor_id', name=op.f('pk_vendor_site_configs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_site_configs')
    op.drop_index('ix_vendor_memberships_vendor_user', table_name='vendor_memberships')
    op.drop_index(op.f('ix_vendor_memberships_vendor_id'), table_name='vendor_memberships')
    op.drop_index(op.f('ix_vendor_memberships_user_id'), table_name='vendor_memberships')
    op.drop_table('vendor_memberships')
    op.drop_index(op.f('ix_vendor_cost_settings_vendor_id'), table_name='vendor_cost_settings')
    op.drop_table('vendor_cost_settings')
    op.drop_index(op.f('ix_qr_logs_vendor_id'), table_name='qr_logs')
    op.drop_table('qr_logs')
    op.drop_index(op.f('ix_outbox_events_vendor_id'), table_name='outbox_events')
    op.drop_index('ix_outbox_events_status_available', table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_inquiries_vendor_id'), table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_index(op.f('ix_cost_estimates_vendor_id'), table_name='cost_estimates')
    op.drop_table('cost_estimates')
    op.drop_index(op.f('ix_callbacks_vendor_id'), table_name='callbacks')
    op.drop_table('callbacks')
    op.drop_index(op.f('ix_applications_vendor_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_vendors_slug'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_processed_events_dedup_hash'), table_name='processed_events')
    op.drop_table('processed_events')
    # Drop enum types last, after every dependent column is gone.
    bind = op.get_bind()
    user_role.drop(bind, checkfirst=True)
    outbox_status.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
